### PR TITLE
Selfoss with cron automated updates

### PR DESCRIPTION
**Pull request by auzias**
We believe that RSS service selfoss should come embedded with an automatic update feature (done through `cron`).
This PR proposes to embed `cron` into the `selfoss` image. As this is not respecting the Docker Best Practice, below are the reasons we still went for this solution.
## Not on the host

In a containerized system there should not be a cron-entry to update a containerized service. Even if the container crashes, `cron` would still try to request the webpage. That is a case we want to avoid. Who is sane enough to let a cron run that automatically fail in some cases?

So we want to containerize the `cron` job. Two solutions comes:
- `cron` in a separate container,
- `cron` in the same container.
## Using Docker compose (`cron` in a separate container)

According to the Docker Best Practice, this feature should be in another container only processing `cron` daemon and should be coupled with compose in order to start both containers: `selfoss` and `cron`. Nevertheless if the container `selfoss` crashes then the container `cron` would still try to request the webpage. This same case we want to avoid.
## Adding `cron` into `selfoss` image

That is not something Docker BP respectful but it overcomes the issue of a container failing while having a error-prone `cron` job. This image:
- adds `cron` to the `selfoss` image,
- appends the cron-job to the `/etc/crontab` file, 
- adds an `/entrypoint.sh` that:
  - starts `cron`,
  - starts `apache2-foreground`.

### CODE REVIEW

**Comment by auzias** [comment]
ping @JensErat

**Comment by JensErat** [comment]
Sorry for the late reply, I was a little bit overwhelmed with work the last days.

I'm not too happy introducing new processes in the Dockerfile, especially as some people might prefer _not_ having a cron daemon running. I'd prefer proposing a `docker-compose` file instead which puts together a selfoss service consisting of a selfoss application container and a cron container (likely with `curl` or `wget` added, so we can send the update query). This way, we'd stick to the one-job-per-container idea and have a simple (and both pluggable and configurable) way to provide updates at the same time.

I don't really see the issues for the unexpected event of a broken selfoss container and a running cron job at the same time -- there will be some failed requests, but no kittens will die (or even worse, containers). Worst thing to expect are some log entries referencing the failed updates.

Have you already looked into "cron" images readily available? It seems there is nothing official around (although putting one together with alpine and curl added together should not be an issue).

**Comment by auzias** [comment]
I agree with you on most points. That's something with discuss a lot with @pamplemousse as we worked together on this.

You're right, there won't be any endangered kittens. That was not our worry though, just that we aim to avoid services that become useless (as one other dies) and failing over. AFAIK there is not any mean to kill a container if another one is stopped/killed. It there were, any we would had done this in a `docker-compose`, I guess.

---

Furthermore the "one service per container" rule is great, nice, makes things easily updat-able, fix-able, upgrad-able, pluggable and custimoz-able. Nevertheless I think that when it's pushed to its limit, it is in fact harmful and hardens the system administration. You suggest to add a `cron` container with `curl` or `wget` through `docker-compose`, but that is two services: `cron` **and** `curl` (or `wget`). The Docker way to solve this would be to run a container as a `cron` job that would run another container with the `curl` (or `wget`). Two and half containers for a RSS reader while one can be enough for this simple service.

Another way to look at this is to consider the "automatically updated" as a feature part of the selfoss service.

That is why, instead of having two and half containers running for "one" service (a rss reader) we merged the `cron`/`curl` services into the `selfoss` one.

For information, this Docker image is available [on the Docker hub](https://hub.docker.com/r/pamplemousse/selfoss/).

---

Are you aware of a mean to stop a container when another is?

**Comment by JensErat** [comment]
Closing this for now, as it does not really discuss requirements on the Docker image/Dockerfile, but is more about application orchestration (pull requests for `docker-compose.yml` files for Docker compose/Docker swarm mode or Kubernetes pod descriptions are welcome, though).

**Pull request closed without merging**
